targets:
    $default:
      builders:
        # reflectable:
        #   generate_for:
        #     - test/**_test.dart
        #     - lib/**.dart
        #     - bin/**.dart
        #   options:
        #     formatted: true
        json_serializable:
            options:
                # Options configure how source code is generated for every
                # `@JsonSerializable`-annotated class in the package.
                #
                # The default value for each is listed.
                any_map: false
                checked: false
                create_factory: true
                create_to_json: true
                disallow_unrecognized_keys: true
                explicit_to_json: false
                field_rename: none
                ignore_unannotated: true
                include_if_null: true
                nullable: true